CC = gcc
CMP = compiler

INCS = -I../src/include

SYNTAB = qin2.syntab
BANK1 = sn-bank-1.raw

.PHONY: all clean cmp

all: compiler
	$(CMP) -ct $(SYNTAB)
	$(CMP) -cw $(BANK1)
	$(CMP) sn-lev120-d1.wav $(BANK1) $(SYNTAB) sn 120 d1
	$(CMP) sn-lev120-e1.wav $(BANK1) $(SYNTAB) sn 120 e1
	$(CMP) sn-lev120-f\#1.wav $(BANK1) $(SYNTAB) sn 120 f\#1
	$(CMP) sn-lev120-a1.wav $(BANK1) $(SYNTAB) sn 120 a1
	$(CMP) sn-lev120-b1.wav $(BANK1) $(SYNTAB) sn 120 b1
	$(CMP) sn-lev120-d2.wav $(BANK1) $(SYNTAB) sn 120 d2
	$(CMP) sn-lev120-e2.wav $(BANK1) $(SYNTAB) sn 120 e2
	$(CMP) sn-lev120-f\#2.wav $(BANK1) $(SYNTAB) sn 120 f\#2
	$(CMP) sn-lev120-a2.wav $(BANK1) $(SYNTAB) sn 120 a2
	$(CMP) sn-lev120-b2.wav $(BANK1) $(SYNTAB) sn 120 b2
	$(CMP) sn-lev120-d3.wav $(BANK1) $(SYNTAB) sn 120 d3
	$(CMP) sn-lev120-e3.wav $(BANK1) $(SYNTAB) sn 120 e3
	$(CMP) sn-lev120-f\#3.wav $(BANK1) $(SYNTAB) sn 120 f\#3
	$(CMP) sn-lev120-a3.wav $(BANK1) $(SYNTAB) sn 120 a3
	$(CMP) sn-lev120-b3.wav $(BANK1) $(SYNTAB) sn 120 b3
	$(CMP) sn-lev120-d4.wav $(BANK1) $(SYNTAB) sn 120 d4
	$(CMP) sn-lev120-e4.wav $(BANK1) $(SYNTAB) sn 120 e4
	$(CMP) sn-lev120-f\#4.wav $(BANK1) $(SYNTAB) sn 120 f\#4
	$(CMP) sn-lev120-a4.wav $(BANK1) $(SYNTAB) sn 120 a4
	$(CMP) sn-lev120-b4.wav $(BANK1) $(SYNTAB) sn 120 b4
	$(CMP) sn-lev120-d5.wav $(BANK1) $(SYNTAB) sn 120 d5
	
	$(CMP) sn-lev100-d1.wav $(BANK1) $(SYNTAB) sn 100 d1
	$(CMP) sn-lev100-e1.wav $(BANK1) $(SYNTAB) sn 100 e1
	$(CMP) sn-lev100-f\#1.wav $(BANK1) $(SYNTAB) sn 100 f\#1
	$(CMP) sn-lev100-a1.wav $(BANK1) $(SYNTAB) sn 100 a1
	$(CMP) sn-lev100-b1.wav $(BANK1) $(SYNTAB) sn 100 b1
	$(CMP) sn-lev100-d2.wav $(BANK1) $(SYNTAB) sn 100 d2
	$(CMP) sn-lev100-e2.wav $(BANK1) $(SYNTAB) sn 100 e2
	$(CMP) sn-lev100-f\#2.wav $(BANK1) $(SYNTAB) sn 100 f\#2
	$(CMP) sn-lev100-a2.wav $(BANK1) $(SYNTAB) sn 100 a2
	$(CMP) sn-lev100-b2.wav $(BANK1) $(SYNTAB) sn 100 b2
	$(CMP) sn-lev100-d3.wav $(BANK1) $(SYNTAB) sn 100 d3
	$(CMP) sn-lev100-e3.wav $(BANK1) $(SYNTAB) sn 100 e3
	$(CMP) sn-lev100-f\#3.wav $(BANK1) $(SYNTAB) sn 100 f\#3
	$(CMP) sn-lev100-a3.wav $(BANK1) $(SYNTAB) sn 100 a3
	$(CMP) sn-lev100-b3.wav $(BANK1) $(SYNTAB) sn 100 b3
	$(CMP) sn-lev100-d4.wav $(BANK1) $(SYNTAB) sn 100 d4
	$(CMP) sn-lev100-e4.wav $(BANK1) $(SYNTAB) sn 100 e4
	$(CMP) sn-lev100-f\#4.wav $(BANK1) $(SYNTAB) sn 100 f\#4
	$(CMP) sn-lev100-a4.wav $(BANK1) $(SYNTAB) sn 100 a4
	$(CMP) sn-lev100-b4.wav $(BANK1) $(SYNTAB) sn 100 b4
	$(CMP) sn-lev100-d5.wav $(BANK1) $(SYNTAB) sn 100 d5
	
	$(CMP) sn-lev72-d1.wav $(BANK1) $(SYNTAB) sn 72 d1
	$(CMP) sn-lev72-e1.wav $(BANK1) $(SYNTAB) sn 72 e1
	$(CMP) sn-lev72-f\#1.wav $(BANK1) $(SYNTAB) sn 72 f\#1
	$(CMP) sn-lev72-a1.wav $(BANK1) $(SYNTAB) sn 72 a1
	$(CMP) sn-lev72-b1.wav $(BANK1) $(SYNTAB) sn 72 b1
	$(CMP) sn-lev72-d2.wav $(BANK1) $(SYNTAB) sn 72 d2
	$(CMP) sn-lev72-e2.wav $(BANK1) $(SYNTAB) sn 72 e2
	$(CMP) sn-lev72-f\#2.wav $(BANK1) $(SYNTAB) sn 72 f\#2
	$(CMP) sn-lev72-a2.wav $(BANK1) $(SYNTAB) sn 72 a2
	$(CMP) sn-lev72-b2.wav $(BANK1) $(SYNTAB) sn 72 b2
	$(CMP) sn-lev72-d3.wav $(BANK1) $(SYNTAB) sn 72 d3
	$(CMP) sn-lev72-e3.wav $(BANK1) $(SYNTAB) sn 72 e3
	$(CMP) sn-lev72-f\#3.wav $(BANK1) $(SYNTAB) sn 72 f\#3
	$(CMP) sn-lev72-a3.wav $(BANK1) $(SYNTAB) sn 72 a3
	$(CMP) sn-lev72-b3.wav $(BANK1) $(SYNTAB) sn 72 b3
	$(CMP) sn-lev72-d4.wav $(BANK1) $(SYNTAB) sn 72 d4
	$(CMP) sn-lev72-e4.wav $(BANK1) $(SYNTAB) sn 72 e4
	$(CMP) sn-lev72-f\#4.wav $(BANK1) $(SYNTAB) sn 72 f\#4
	$(CMP) sn-lev72-a4.wav $(BANK1) $(SYNTAB) sn 72 a4
	$(CMP) sn-lev72-b4.wav $(BANK1) $(SYNTAB) sn 72 b4
	$(CMP) sn-lev72-d5.wav $(BANK1) $(SYNTAB) sn 72 d5
	
	$(CMP) sn-lev52-d1.wav $(BANK1) $(SYNTAB) sn 52 d1
	$(CMP) sn-lev52-e1.wav $(BANK1) $(SYNTAB) sn 52 e1
	$(CMP) sn-lev52-f\#1.wav $(BANK1) $(SYNTAB) sn 52 f\#1
	$(CMP) sn-lev52-a1.wav $(BANK1) $(SYNTAB) sn 52 a1
	$(CMP) sn-lev52-b1.wav $(BANK1) $(SYNTAB) sn 52 b1
	$(CMP) sn-lev52-d2.wav $(BANK1) $(SYNTAB) sn 52 d2
	$(CMP) sn-lev52-e2.wav $(BANK1) $(SYNTAB) sn 52 e2
	$(CMP) sn-lev52-f\#2.wav $(BANK1) $(SYNTAB) sn 52 f\#2
	$(CMP) sn-lev52-a2.wav $(BANK1) $(SYNTAB) sn 52 a2
	$(CMP) sn-lev52-b2.wav $(BANK1) $(SYNTAB) sn 52 b2
	$(CMP) sn-lev52-d3.wav $(BANK1) $(SYNTAB) sn 52 d3
	$(CMP) sn-lev52-e3.wav $(BANK1) $(SYNTAB) sn 52 e3
	$(CMP) sn-lev52-f\#3.wav $(BANK1) $(SYNTAB) sn 52 f\#3
	$(CMP) sn-lev52-a3.wav $(BANK1) $(SYNTAB) sn 52 a3
	$(CMP) sn-lev52-b3.wav $(BANK1) $(SYNTAB) sn 52 b3
	$(CMP) sn-lev52-d4.wav $(BANK1) $(SYNTAB) sn 52 d4
	$(CMP) sn-lev52-e4.wav $(BANK1) $(SYNTAB) sn 52 e4
	$(CMP) sn-lev52-f\#4.wav $(BANK1) $(SYNTAB) sn 52 f\#4
	$(CMP) sn-lev52-a4.wav $(BANK1) $(SYNTAB) sn 52 a4
	$(CMP) sn-lev52-b4.wav $(BANK1) $(SYNTAB) sn 52 b4
	$(CMP) sn-lev52-d5.wav $(BANK1) $(SYNTAB) sn 52 d5
	
	$(CMP) sn-lev48-d1.wav $(BANK1) $(SYNTAB) sn 48 d1
	$(CMP) sn-lev48-e1.wav $(BANK1) $(SYNTAB) sn 48 e1
	$(CMP) sn-lev48-f\#1.wav $(BANK1) $(SYNTAB) sn 48 f\#1
	$(CMP) sn-lev48-a1.wav $(BANK1) $(SYNTAB) sn 48 a1
	$(CMP) sn-lev48-b1.wav $(BANK1) $(SYNTAB) sn 48 b1
	$(CMP) sn-lev48-d2.wav $(BANK1) $(SYNTAB) sn 48 d2
	$(CMP) sn-lev48-e2.wav $(BANK1) $(SYNTAB) sn 48 e2
	$(CMP) sn-lev48-f\#2.wav $(BANK1) $(SYNTAB) sn 48 f\#2
	$(CMP) sn-lev48-a2.wav $(BANK1) $(SYNTAB) sn 48 a2
	$(CMP) sn-lev48-b2.wav $(BANK1) $(SYNTAB) sn 48 b2
	$(CMP) sn-lev48-d3.wav $(BANK1) $(SYNTAB) sn 48 d3
	$(CMP) sn-lev48-e3.wav $(BANK1) $(SYNTAB) sn 48 e3
	$(CMP) sn-lev48-f\#3.wav $(BANK1) $(SYNTAB) sn 48 f\#3
	$(CMP) sn-lev48-a3.wav $(BANK1) $(SYNTAB) sn 48 a3
	$(CMP) sn-lev48-b3.wav $(BANK1) $(SYNTAB) sn 48 b3
	$(CMP) sn-lev48-d4.wav $(BANK1) $(SYNTAB) sn 48 d4
	$(CMP) sn-lev48-e4.wav $(BANK1) $(SYNTAB) sn 48 e4
	$(CMP) sn-lev48-f\#4.wav $(BANK1) $(SYNTAB) sn 48 f\#4
	$(CMP) sn-lev48-a4.wav $(BANK1) $(SYNTAB) sn 48 a4
	$(CMP) sn-lev48-b4.wav $(BANK1) $(SYNTAB) sn 48 b4
	$(CMP) sn-lev48-d5.wav $(BANK1) $(SYNTAB) sn 48 d5
	
compiler: ./cmp/compiler.c
	$(CC) $< $(INCS) -o $@

clean:
	@rm ./qin2.syntab
